# PlatformIO Project Configuration File
#
#   Build options: build flags, source filter
#   Upload options: custom upload port, speed and extra flags
#   Library options: dependencies, extra library storages
#   Advanced options: extra scripting
#
# Please visit documentation for the other options and examples
# https://docs.platformio.org/page/projectconf.html

[platformio] 
default_envs = selected # Comment to build all environments
extra_configs = 
	src/config/DJthefirst/*.ini
	src/config/Example/*.ini
	src/config/User/*.ini

[teensy41]
platform = teensy
framework = arduino
board = teensy41

[esp32dev]
platform = espressif32
framework = arduino
board = esp32dev

#---------- Uncomment Your Selected Instrument Configuration ----------

[env:selected]
; extends = teensy41, Dulcimer_teensy41
; extends = esp32dev, Dulcimer_esp32dev
; extends = teensy41, FloppySynth_teensy41
; extends = esp32dev, FloppySynth_esp32dev
; extends = teensy41, StepperSynthHw_teensy41
; extends = esp32dev, StepperSynthHw_esp32dev
; extends = teensy41, Example_teensy41
; extends = esp32dev, Example_esp32dev
; extends = teensy41, MultiPhase_teensy41
; extends = esp32dev, MultiPhase_esp32dev
; extends = teensy41, FloppyDrive_teensy41
; extends = esp32dev, FloppyDrive_esp32dev
; extends = teensy41, StepSw_teensy41
; extends = esp32dev, StepSw_esp32dev
; extends = teensy41, StepSwShift_teensy41
; extends = esp32dev, StepSwShift_esp32dev
; extends = teensy41, PwmHw_teensy41
extends = esp32dev, PwmHw_esp32dev
; extends = teensy41, PwmSw_teensy41
; extends = esp32dev, PwmSw_esp32dev
; extends = teensy41, PneumaticValves_teensy41
; extends = esp32dev, PneumaticValves_esp32dev
; extends = teensy41, Teensy41HwPwm_teensy41
; extends = esp32dev, Teensy41HwPwm_esp32dev
; extends = teensy41, Teensy41SwPwm_teensy41
; extends = esp32dev, Teensy41SwPwm_esp32dev

[env:Dulcimer_teensy41]
extends = teensy41, Dulcimer_teensy41

[env:Dulcimer_esp32dev]
extends = esp32dev, Dulcimer_esp32dev

[env:FloppySynth_teensy41]
extends = teensy41, FloppySynth_teensy41

[env:FloppySynth_esp32dev]
extends = esp32dev, FloppySynth_esp32dev

[env:StepperSynthHw_teensy41]
extends = teensy41, StepperSynthHw_teensy41

[env:StepperSynthHw_esp32dev]
extends = esp32dev, StepperSynthHw_esp32dev

[env:MultiPhase_teensy41]
extends = teensy41, MultiPhase_teensy41

[env:MultiPhase_esp32dev]
extends = esp32dev, MultiPhase_esp32dev

[env:FloppyDrive_teensy41]
extends = teensy41, FloppyDrive_teensy41

[env:FloppyDrive_esp32dev]
extends = esp32dev, FloppyDrive_esp32dev

[env:StepSw_teensy41]
extends = teensy41, StepSw_teensy41

[env:StepSw_esp32dev]
extends = esp32dev, StepSw_esp32dev

[env:StepSwShift_teensy41]
extends = teensy41, StepSwShift_teensy41

[env:StepSwShift_esp32dev]
extends = esp32dev, StepSwShift_esp32dev

[env:PwmHw_teensy41]
extends = teensy41, PwmHw_teensy41

[env:PwmHw_esp32dev]
extends = esp32dev, PwmHw_esp32dev

[env:PwmSw_teensy41]
extends = teensy41, PwmSw_teensy41

[env:PwmSw_esp32dev]
extends = esp32dev, PwmSw_esp32dev

[env:PneumaticValves_teensy41]
extends = teensy41, PneumaticValves_teensy41

[env:PneumaticValves_esp32dev]
extends = esp32dev, PneumaticValves_esp32dev

[env:Teensy41HwPwm_teensy41]
extends = teensy41, Teensy41HwPwm_teensy41

[env:Teensy41HwPwm_esp32dev]
extends = esp32dev, Teensy41HwPwm_esp32dev

[env:Teensy41SwPwm_teensy41]
extends = teensy41, Teensy41SwPwm_teensy41

[env:Teensy41SwPwm_esp32dev]
extends = esp32dev, Teensy41SwPwm_esp32dev

