# PlatformIO Project Configuration File
#
#   Build options: build flags, source filter
#   Upload options: custom upload port, speed and extra flags
#   Library options: dependencies, extra library storages
#   Advanced options: extra scripting
#
# Please visit documentation for the other options and examples
# https://docs.platformio.org/page/projectconf.html

[platformio] 
extra_configs = 
	src/config/DJthefirst/*.ini
	src/config/Example/*.ini
	src/config/User/*.ini

[teensy41]
platform = teensy
framework = arduino
board = teensy41

[esp32dev]
platform = espressif32
framework = arduino
board = esp32dev

#---------- Uncomment Your Selected Instrument Configuration ----------

[env:selected]
extends = teensy41, Dulcimer_teensy41
; extends = esp32dev, Dulcimer_esp32dev
; extends = teensy41, FloppySynth_teensy41
; extends = esp32dev, FloppySynth_esp32dev

