; PlatformIO Project PneumaticValves Configuration File

[PneumaticValves]
#---------- Device Configuration ----------
device_cfg = 
    -D CFG_DEVICE_NAME="\"Teensy Pneu Valves\""
    -D CFG_DEVICE_ID=0x00018

#---------- Instrument Configuration ----------
instrument_cfg =
    -D CFG_INSTRUMENT_TYPE_VALUE="\"Instruments/DJthefirst/PneumaticValvesSw.h\""

    -D CFG_NUM_INSTRUMENTS=8 #Max Number of Instrument groups is 32
    -D CFG_NUM_SUBINSTRUMENTS=1 #Multiplies Instrument groups into individual instruments
    -D CFG_MIN_NOTE=0 #Absolute Lowest Note Min=0
    -D CFG_MAX_NOTE=127 #Absolute Highest Note Max=127
	-D CFG_NOTE_TIMEOUT_MS=10000 #Maximun duration of a sustained note incase of stuck notes (0 to disable) 
	-D CFG_VIBRATO_ENABLED

#---------- Network Configuration ----------
network_serial =
	-D CFG_MMM_NETWORK_SERIAL
    -D CFG_MMM_NETWORK_SERIAL_BAUD=115200 # Standard MIDI baud rate

network_udp =
	-D CFG_MMM_NETWORK_UDP
	-D CFG_MMM_NETWORK_UDP_AsyncWebServer_PORT=80 # Default AsyncWebServer port
	-D CFG_MMM_NETWORK_UDP_ADDRESS="{224, 5, 6, 7}" # Default local network IP
	-D CFG_MMM_NETWORK_UDP_OTA_PORT=8337 # Default UDP port for MIDI

network_usb =
	-D CFG_MMM_NETWORK_USB

network_din =
	-D CFG_MMM_NETWORK_DIN

#---------- Components Configuration ----------
component_pwm = 
	-D CFG_PWM_NOTES_DOUBLE

#---------- Extras Configuration ----------
extra_local_storage =
	-D CFG_EXTRA_LOCAL_STORAGE

extra_addr_leds =
	-D CFG_EXTRA_ADDRESSABLE_LEDS
	-D CFG_NUM_LEDS=8
	-D CFG_BRIGHTNESS=255
	-D CFG_LED_TYPE=WS2811
	-D CFG_COLOR_ORDER=GRB
	-D CFG_UPDATES_PER_SECOND=100

#---------- PlatformIO Configuration ----------
framework = arduino
build_unflags = -std=gnu++11
build_flags = 
	-std=gnu++17
	${PneumaticValves.device_cfg}
	${PneumaticValves.instrument_cfg}

	# Network Configurations
	${PneumaticValves.network_serial}
	; ${PneumaticValves.network_udp}
	; ${PneumaticValves.network_usb}
	; ${PneumaticValves.network_din}

	# Components Configurations
	${PneumaticValves.component_pwm}

	# Extras Configurations
	${PneumaticValves.extra_local_storage}
	; ${PneumaticValves.extra_addr_leds}

monitor_speed = 115200

lib_deps = 
	fastled/FastLED@^3.5.0
	; 4-20ma/ModbusMaster@^2.0.1
	; robtillaart/AD9833@^0.4.0
  	;lathoub/AppleMIDI@^3.3.0
	;lathoub/BLE-MIDI@^2.2

check_flags = --enable=all --suppress=unusedFunction

########## ESP32 Dev CONFIGURATION ##########
[PneumaticValves_esp32dev]
extends = PneumaticValves

#---------- Hardware Configuration ----------
build_flags = 
	${PneumaticValves.build_flags}
	-D CFG_TIMER_RESOLUTION_US=8
	-D CFG_PINS_INSTRUMENT_PWM="2,4,18,19,21,23,22,28"
    -D CFG_PIN_LED_DATA=33

########## TEENSY 4.1 CONFIGURATION ##########
[PneumaticValves_teensy41]
extends = PneumaticValves

#---------- Hardware Configuration ----------
build_flags = 
	${PneumaticValves.build_flags}
	-D CFG_TIMER_RESOLUTION_US=1
	-D CFG_PINS_INSTRUMENT_PWM="1,4,3,2,5,6,7,8"
    -D CFG_PIN_LED_DATA=29