; PlatformIO Project SolenoidShiftReg Configuration File

[SolenoidShiftReg]
#---------- Device Configuration ----------
device_cfg = 
    -D CFG_DEVICE_NAME="\"Solenoid Shift Reg\""
    -D CFG_DEVICE_ID=0x00020

#---------- Instrument Configuration ----------
instrument_cfg =
    -D CFG_INSTRUMENT_TYPE_VALUE="\"Instruments/DJthefirst/SolenoidShiftReg.h\""

    -D CFG_NUM_INSTRUMENTS=36 #Max Number of Instrument groups is 32
    -D CFG_NUM_SUBINSTRUMENTS=1 #Multiplies Instrument groups into individual instruments
    -D CFG_MIN_NOTE=48 #C3
    -D CFG_MAX_NOTE=83 #B5
	-D CFG_NOTE_TIMEOUT_MS=10000 #Maximum duration of a sustained note in case of stuck notes (0 to disable) 

#---------- Network Configuration ----------
network_serial =
	-D CFG_MMM_NETWORK_SERIAL
    -D CFG_MMM_NETWORK_SERIAL_BAUD=115200 # Standard MIDI baud rate

network_udp =
	-D CFG_MMM_NETWORK_UDP
	-D CFG_MMM_NETWORK_UDP_AsyncWebServer_PORT=80 # Default AsyncWebServer port
	-D CFG_MMM_NETWORK_UDP_ADDRESS="{224, 5, 6, 7}" # Default local network IP
	-D CFG_MMM_NETWORK_UDP_OTA_PORT=8337 # Default UDP port for MIDI

network_usb =
	-D CFG_MMM_NETWORK_USB

network_din =
	-D CFG_MMM_NETWORK_DIN

#---------- Components Configuration ----------
shift_register =
	-D CFG_SHIFTREG_TYPE=DEFAULT
	; -D CFG_SHIFTREG_TYPE=HW_ACCEL
	-D CFG_SHIFTREG_HOLDTIME_NS=25

#---------- Extras Configuration ----------
extra_local_storage =
	-D CFG_EXTRA_LOCAL_STORAGE

extra_addr_leds =
	-D CFG_EXTRA_ADDRESSABLE_LEDS
	-D CFG_NUM_LEDS=36
	-D CFG_BRIGHTNESS=255
	-D CFG_LED_TYPE=WS2812B
	-D CFG_COLOR_ORDER=GRB
	-D CFG_UPDATES_PER_SECOND=100

#---------- PlatformIO Configuration ----------
framework = arduino
build_unflags = -std=gnu++11
build_flags = 
	-std=gnu++17
	${SolenoidShiftReg.device_cfg}
	${SolenoidShiftReg.instrument_cfg}

	# Network Configurations
	${SolenoidShiftReg.network_serial}
	; ${SolenoidShiftReg.network_udp}
	; ${SolenoidShiftReg.network_usb}
	; ${SolenoidShiftReg.network_din}

	# Components Configurations
	${SolenoidShiftReg.shift_register}

	# Extras Configurations
	${SolenoidShiftReg.extra_local_storage}
	${SolenoidShiftReg.extra_addr_leds}

monitor_speed = 115200

lib_deps = 
	fastled/FastLED@^3.5.0

check_flags = --enable=all --suppress=unusedFunction

########## ESP32 Dev CONFIGURATION ##########
[SolenoidShiftReg_esp32dev]
extends = SolenoidShiftReg

#---------- Hardware Configuration ----------
build_flags = 
	${SolenoidShiftReg.build_flags}
	-D CFG_TIMER_RESOLUTION_US=8
	; First Shift Register (C3-B4, 24 outputs)
	-D CFG_SHIFTREG1_PIN_SER=13
	-D CFG_SHIFTREG1_PIN_CLK=14
	-D CFG_SHIFTREG1_PIN_LD=15
	-D CFG_SHIFTREG1_PIN_EN=16
	-D CFG_SHIFTREG1_PIN_RST=17
	; Second Shift Register (C5-B5, 12 outputs)
	-D CFG_SHIFTREG2_PIN_SER=25
	-D CFG_SHIFTREG2_PIN_CLK=26
	-D CFG_SHIFTREG2_PIN_LD=27
	-D CFG_SHIFTREG2_PIN_EN=32
	-D CFG_SHIFTREG2_PIN_RST=33
    -D CFG_PIN_LED_DATA=12

########## TEENSY 4.1 CONFIGURATION ##########
[SolenoidShiftReg_teensy41]
extends = SolenoidShiftReg

#---------- Hardware Configuration ----------
build_flags = 
	${SolenoidShiftReg.build_flags}
	-D CFG_TIMER_RESOLUTION_US=8
	; First Shift Register (C3-B4, 24 outputs)
	-D CFG_SHIFTREG1_PIN_SER=2
	-D CFG_SHIFTREG1_PIN_CLK=3
	-D CFG_SHIFTREG1_PIN_LD=4
	-D CFG_SHIFTREG1_PIN_EN=5
	-D CFG_SHIFTREG1_PIN_RST=6
	; Second Shift Register (C5-B5, 12 outputs)
	-D CFG_SHIFTREG2_PIN_SER=7
	-D CFG_SHIFTREG2_PIN_CLK=8
	-D CFG_SHIFTREG2_PIN_LD=9
	-D CFG_SHIFTREG2_PIN_EN=10
	-D CFG_SHIFTREG2_PIN_RST=11
    -D CFG_PIN_LED_DATA=24
