#include "Config.h"

#if defined(PLATFORM_TEENSY41) && defined(SHIFTREG_USE_FLEXIO) && defined(COMPONENT_SHIFTREG_74HC595)

#endif // PLATFORM_TEENSY41 && SHIFTREG_USE_FLEXIO && COMPONENT_SHIFTREG_74HC595