; PlatformIO Project SWPwm Configuration File

[PwmSw]
#---------- Device Configuration ----------
device_cfg =
    -D CFG_DEVICE_NAME="\"Software PWM\""
    -D CFG_DEVICE_ID=0x0018

#---------- Instrument Configuration ----------
instrument_cfg =
    -D CFG_INSTRUMENT_SWPWM
    -D CFG_INSTRUMENT_TYPE_VALUE="\"Instruments/Base/PWM/PWM.h\""
    ; -D CFG_NUM_INSTRUMENTS=8
    -D CFG_NUM_SUBINSTRUMENTS=1
    -D CFG_MIN_NOTE=0
    -D CFG_MAX_NOTE=127
    -D CFG_NOTE_TIMEOUT_MS=10000

#---------- Network Configuration ----------
network_serial =
    -D CFG_MMM_NETWORK_SERIAL
    -D CFG_MMM_NETWORK_SERIAL_BAUD=115200

network_udp =
    -D CFG_MMM_NETWORK_UDP
    -D CFG_MMM_NETWORK_UDP_AsyncWebServer_PORT=80
    -D CFG_MMM_NETWORK_UDP_ADDRESS="{224, 5, 6, 7}"
    -D CFG_MMM_NETWORK_UDP_OTA_PORT=8337

network_usb =
    -D CFG_MMM_NETWORK_USB

network_din =
    -D CFG_MMM_NETWORK_DIN

#---------- Components Configuration ----------
component_pwm =
    -D CFG_COMPONENT_PWM
    -D CFG_PWM_TYPE=DEFAULT
    ; -D CFG_PWM_TYPE=HW_ACCEL
    ; -D CFG_PWM_TYPE=FLEXIO
    ; Hardware timer/pin map is defined per-board in each HW section

#---------- Extras Configuration ----------
extra_local_storage =
    -D CFG_EXTRA_LOCAL_STORAGE

extra_addr_leds =
    -D CFG_EXTRA_ADDRESSABLE_LEDS
    -D CFG_NUM_LEDS=64
    -D CFG_BRIGHTNESS=255
    -D CFG_LED_TYPE=WS2811
    -D CFG_COLOR_ORDER=GRB
    -D CFG_UPDATES_PER_SECOND=10

#---------- PlatformIO Configuration ----------
framework = arduino
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    ${PwmSw.device_cfg}
    ${PwmSw.instrument_cfg}
    ${PwmSw.network_serial}
    ; ${PwmSw.network_udp}
    ; ${PwmSw.network_usb}
    ; ${PwmSw.network_din}
    ${PwmSw.component_pwm}
    ; ${PwmSw.extra_local_storage}
    ; ${PwmSw.extra_addr_leds}

monitor_speed = 115200

########## ESP32 Dev CONFIGURATION ##########
[PwmSw_esp32dev]
extends = PwmSw

#---------- Hardware Configuration ----------
build_flags =
    ${PwmSw.build_flags}
    -D CFG_NUM_INSTRUMENTS=8
    -D CFG_TIMER_RESOLUTION_US=8
    -D CFG_PINS_INSTRUMENT_PWM="2,4,18,19,21,22,23,25"
    -D CFG_PIN_LED_DATA=18

########## TEENSY 4.1 CONFIGURATION ##########
[PwmSw_teensy41]
extends = PwmSw

#---------- Hardware Configuration ----------
build_flags =
    ${PwmSw.build_flags}
    -D CFG_NUM_INSTRUMENTS=12
    -D CFG_TIMER_RESOLUTION_US=1
    -D CFG_PINS_INSTRUMENT_PWM="1,2,3,4,5,6,7,8,9,10,11,12"
    -D CFG_PIN_LED_DATA=13
