; PlatformIO Project StepSwShift Configuration File
; Converted from StepSwShiftCfg.h (header file is empty).

[StepSwShift]
instrument_cfg =
    -D CFG_INSTRUMENT_STEPSWSHIFT
    -D CFG_INSTRUMENT_STEPSW
    -D CFG_INSTRUMENT_SWPWM
    -D CFG_INSTRUMENT_TYPE_VALUE="\"Instruments/Base/StepSwShift/StepSwShift.h\""

framework = arduino
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    ${StepSwShift.instrument_cfg}

monitor_speed = 115200

[StepSwShift_teensy41]
extends = StepSwShift

#---------- Hardware Configuration ----------
build_flags =
    ${StepSwShift.build_flags}

########## ESP32 Dev CONFIGURATION ##########
[StepSwShift_esp32dev]
extends = StepSwShift

#---------- Hardware Configuration ----------
build_flags =
    ${StepSwShift.build_flags}
