; PlatformIO Project StepSw Configuration File

[StepSw]
#---------- Device Configuration ----------
device_cfg =
    -D CFG_DEVICE_NAME="\"Step SW PWM\""
    -D CFG_DEVICE_ID=0x0033

#---------- Instrument Configuration ----------
instrument_cfg =
    -D CFG_INSTRUMENT_TYPE_VALUE="\"Instruments/Base/StepSw/StepSw.h\""
    -D CFG_NUM_INSTRUMENTS=8
    -D CFG_NUM_SUBINSTRUMENTS=1
    -D CFG_MIN_NOTE=0
    -D CFG_MAX_NOTE=127
    -D CFG_NOTE_TIMEOUT_MS=10000

#---------- Network Configuration ----------
network_serial =
    -D CFG_MMM_NETWORK_SERIAL
    -D CFG_MMM_NETWORK_SERIAL_BAUD=115200

network_udp =
    -D CFG_MMM_NETWORK_UDP
    -D CFG_MMM_NETWORK_UDP_AsyncWebServer_PORT=80
    -D CFG_MMM_NETWORK_UDP_ADDRESS="{224, 5, 6, 7}"
    -D CFG_MMM_NETWORK_UDP_OTA_PORT=8337

network_usb =
    -D CFG_MMM_NETWORK_USB

network_din =
    -D CFG_MMM_NETWORK_DIN

#---------- Components Configuration ----------
component_pwm =
    -D CFG_PWM_NOTES_DOUBLE
    ; Hardware timer/pin map is defined per-board in each HW section

component_step_limits =
    ; -D CFG_STEP_MIN_POS=0
    ; -D CFG_STEP_MAX_POS=150
    ; Hardware pin map is defined per-board in each HW section

#---------- Extras Configuration ----------
extra_local_storage =
    -D CFG_EXTRA_LOCAL_STORAGE

extra_addr_leds =
    -D CFG_EXTRA_ADDRESSABLE_LEDS
    -D CFG_NUM_LEDS=64
    -D CFG_BRIGHTNESS=255
    -D CFG_LED_TYPE=WS2811
    -D CFG_COLOR_ORDER=GRB
    -D CFG_UPDATES_PER_SECOND=10

#---------- PlatformIO Configuration ----------
framework = arduino
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    ${StepSw.device_cfg}
    ${StepSw.instrument_cfg}
    ${StepSw.network_serial}
    ; ${StepSw.network_udp}
    ; ${StepSw.network_usb}
    ; ${StepSw.network_din}
    ${StepSw.component_pwm}
    ${StepSw.component_step_limits}
    ${StepSw.extra_local_storage}
    ; ${StepSw.extra_addr_leds}

monitor_speed = 115200

########## TEENSY 4.1 CONFIGURATION ##########
[StepSw_teensy41]
extends = StepSw

#---------- Hardware Configuration ----------
build_flags =
    ${StepSw.build_flags}
    -D CFG_TIMER_RESOLUTION_US=1
    -D CFG_PINS_INSTRUMENT_PWM="0,2,4,6,8,10,14,18"
    -D CFG_PINS_INSTRUMENT_DIR="1,3,5,7,9,11,15,19"
    -D CFG_PIN_LED_DATA=13

########## ESP32 Dev CONFIGURATION ##########
[StepSw_esp32dev]
extends = StepSw

#---------- Hardware Configuration ----------
build_flags =
    ${StepSw.build_flags}
    -D CFG_TIMER_RESOLUTION_US=8
    -D CFG_PINS_INSTRUMENT_PWM="1,3,5,7,9,11,13,15"
    -D CFG_PINS_INSTRUMENT_DIR="2,4,6,8,10,12,14,16"
    -D CFG_PIN_LED_DATA=18
